// Generated by CoffeeScript 1.7.1
'use strict';
describe('Controller: MainCtrl', function() {
  var MainCtrl, scope;
  beforeEach(module('timetrackerApp'));
  MainCtrl = {};
  scope = {};
  beforeEach(inject(function($controller, $rootScope) {
    scope = $rootScope.$new();
    return MainCtrl = $controller('MainCtrl', {
      $scope: scope
    });
  }));
  return it('contains spec with an expectation', function() {
    return expect(true).toBe(true);
  });
});
