// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('timetrackerApp', ['ngCookies', 'ngResource', 'ngSanitize', 'ngRoute', 'firebase']).config(function($routeProvider) {
  return $routeProvider.when('/', {
    templateUrl: 'views/main.html',
    controller: 'MainCtrl'
  }).otherwise({
    redirectTo: '/'
  });
});
